name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    deploy-to-dev:
        name: Deploy to dev
        runs-on: ubuntu-latest
        environment: dev
        uses: ./.github/workflows/test.yml

    deploy-to-stg:
        name: Deploy to stg
        runs-on: ubuntu-latest
        needs:
            - deploy-to-dev
        environment: stg
        uses: ./.github/workflows/test.yml
