name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    deploy-to-dev:
        name: Deploy to dev
        runs-on: ubuntu-latest
        environment: dev
        steps:
           - uses: ./.github/workflows/test.yml

    deploy-to-stg:
        name: Deploy to dev
        runs-on: ubuntu-latest
        environment: stg
        steps:
            - uses: ./.github/workflows/test.yml
